linkedin: "https://www.linkedin.com/in/alejandro-gomez-lagunas-12748212/"
github: "https://github.com/agomezguru"
email: "alagunas@coati.com.mx"
name: "agomezguru"
about:
  Passionate about superb music recordings (high end audio equipment enthusiast), love walking
  outdoors or in a isolated beach, I like swimming, poetry, literature and a good conversation.
real_name: Alejandro Gómez Lagunas
location: Oaxaca, Méx.
phone: +52 (951) 228-6616
hours: "**Mon-Sat:** 11:30AM - 5:00PM"
