linkedin: "https://www.linkedin.com/in/alejandro-gomez-lagunas-12748212/"
github: "https://github.com/agomezguru"
email: "alagunas@coati.com.mx"
name: "agomezguru"
location: Oaxaca, Méx.
phone: +52 (951) 228-6616
hours: "**Mon-Sat:** 11:30AM - 5:00PM"
