main:
  - identifier: categories
    name: Temas
    url: /temas
    weight: 100
    post: El origen de este blog
  - identifier: contact
    name: Contáctame
    url: /contacto
    weight: 200
    post: A su servicio
footer: 
  - name: Privacy Policy 
    weight: 300 
    url: /privacy 
  - name: Terms of Use 
    weight: 200 
    url: /terms