main:
  - identifier: home
    name: Inicio
    url: /
    weight: 100
    post: Ir al inicio

  - identifier: more
    name: ver más
    url: /more
    weight: 400
    post: Ir al blog

  - identifier: contact
    name: Contáctame
    url: /contacto
    weight: 500
    post: A su servicio

footer: 
  - name: Privacy Policy 
    weight: 100 
    url: /privacy 
  - name: Terms of Use 
    weight: 200 
    url: /terms
